; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TurnEdit"
#define MyAppVersion "1.7"
#define MyAppExeName "TurnEdit.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{52F9CAEC-2EF3-421C-84CF-6D888FACC6C0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
LicenseFile=C:\youmu\projects\turnedit-wpf\license.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=turnedit-setup
SolidCompression=yes
WizardStyle=classic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\bin\Release\net9.0-windows\win-x64\publish\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\turnedit-icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\youmu\projects\turnedit-updater\bin\Release\net9.0-windows\win-x64\TurnEditUpdater.exe"; DestDir: "{app}"; Flags: ignoreversion onlyifdoesntexist
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\japanese\turnedit-settings.json"; DestDir: "{userappdata}\TurnEdit"; Flags: ignoreversion onlyifdoesntexist; Languages: japanese
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\english\turnedit-settings.json"; DestDir: "{userappdata}\TurnEdit"; Flags: ignoreversion onlyifdoesntexist; Languages: english
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Dirs]
Name: "{app}\plugins"
Name: "{app}\checksums" 

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

