; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TurnEdit"
#define MyAppVersion "2.0-alpha.1"
#define MyAppExeName "TurnEdit.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{52F9CAEC-2EF3-421C-84CF-6D888FACC6C0}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher=TurnApps
AppPublisherURL=https://turnapps.f5.si
SetupIconFile=C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\TurnEdit-Setup.ico
;AppVerName={#MyAppName} {#MyAppVersion}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
MinVersion=10.0.19045
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
DisableWelcomePage=no
WizardImageFile=C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\setup-cover.png
WizardImageFileDynamicDark=C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\setup-cover.png
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
UsePreviousAppDir=yes
DisableProgramGroupPage=no
AppendDefaultDirName=yes
LicenseFile=C:\youmu\projects\turnedit-wpf\license.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputBaseFilename=turnedit-setup
SolidCompression=yes
WizardStyle=modern dynamic windows11
InfoBeforeFile=C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\release-note.txt
CloseApplications=yes
CloseApplicationsFilter=TurnEdit.exe
PrivilegesRequiredOverridesAllowed=dialog commandline
AllowUNCPath=yes
[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\bin\Release\net10.0-windows7.0\win-x64\publish\*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs ignoreversion
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\turnedit-icon.ico"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\japanese\turnedit-settings.json"; DestDir: "{userappdata}\TurnEdit"; Flags: ignoreversion onlyifdoesntexist; Languages: japanese
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\english\turnedit-settings.json"; DestDir: "{userappdata}\TurnEdit"; Flags: ignoreversion onlyifdoesntexist; Languages: english
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\spanish\turnedit-settings.json"; DestDir: "{userappdata}\TurnEdit"; Flags: ignoreversion onlyifdoesntexist; Languages: spanish
Source: "C:\youmu\projects\turnedit-wpf\TurnEdit\TurnEdit\korean\turnedit-settings.json"; DestDir: "{userappdata}\TurnEdit"; Flags: ignoreversion onlyifdoesntexist; Languages: korean

[Dirs]
Name: "{app}\plugins"
Name: "{app}\checksums"

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

