<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>turnedit-icon.ico</ApplicationIcon>
    <Version>2.0-alpha.1</Version>
    <AssemblyVersion>2.0</AssemblyVersion>
    <FileVersion>2.0-alpha.1</FileVersion>
	<Copyright>Copyright ©️ 2025 TheBlockPilot All rights reserved.</Copyright>
	<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
	<ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="EasterEgg.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="turnedit-icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="EasterEgg.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
    <PackageReference Include="Google.GenAI" Version="0.9.0" />
    <PackageReference Include="OpenAI-DotNet" Version="8.8.7" />
    <PackageReference Include="UTF.Unknown" Version="2.6.0" />
    <PackageReference Include="WPF-UI" Version="4.1.0" />
  </ItemGroup>

</Project>
